Repository dowjones/hammer, pull requests merged in 2018-08, with the labels that each got.

#2 terraform docs update for issue #1
  docs/pages/deployment_terraform.md
Labels: documentation

#4 Feature: limit remediation accounts
  deployment/configs/config.json
  docs/pages/editconfig.md
  docs/pages/playbook1_s3_public_buckets_acl.md
  docs/pages/playbook2_insecure_services.md
  docs/pages/playbook3_inactive_user_keys.md
  docs/pages/playbook4_keysrotation.md
  docs/pages/playbook5_s3_public_buckets_policy.md
  docs/pages/playbook8_ebs_snapshots_public.md
  docs/pages/playbook9_rds_snapshots_public.md
  hammer/library/config.py
  hammer/reporting-remediation/remediation/clean_iam_key_rotation.py
  hammer/reporting-remediation/remediation/clean_iam_keys_inactive.py
  hammer/reporting-remediation/remediation/clean_public_ebs_snapshots.py
  hammer/reporting-remediation/remediation/clean_public_rds_snapshots.py
  hammer/reporting-remediation/remediation/clean_s3bucket_acl_permissions.py
  hammer/reporting-remediation/remediation/clean_s3bucket_policy_permissions.py
  hammer/reporting-remediation/remediation/clean_security_groups.py
  hammer/reporting-remediation/reporting/create_cloudtrail_tickets.py
  hammer/reporting-remediation/reporting/create_ebs_public_snapshot_issue_tickets.py
  hammer/reporting-remediation/reporting/create_ebs_volume_issue_tickets.py
  hammer/reporting-remediation/reporting/create_iam_key_inactive_tickets.py
  hammer/reporting-remediation/reporting/create_iam_key_rotation_tickets.py
  hammer/reporting-remediation/reporting/create_rds_public_snapshot_issue_tickets.py
  hammer/reporting-remediation/reporting/create_s3bucket_acl_issue_tickets.py
  hammer/reporting-remediation/reporting/create_s3bucket_policy_issue_tickets.py
  hammer/reporting-remediation/reporting/create_security_groups_tickets.py
Labels: enhancement

#3 Feature: region autodetection
  docs/pages/deployment_terraform.md
  docs/pages/editconfig.md
  hammer/identification/lambdas/ami-info/requirements.txt
  hammer/identification/lambdas/requirements.txt
  hammer/library/config.py
Labels: enhancement

#5 Feature: slackbot
  deployment/cf-templates/reporting-remediation.json
  docs/pages/editconfig.md
  hammer/library/slack_utility.py
  hammer/reporting-remediation/analytics/security_issues_csv_report.py
  hammer/reporting-remediation/bot/commands.py
  hammer/reporting-remediation/bot/hammer-bot.service
  hammer/reporting-remediation/bot/run.py
  hammer/reporting-remediation/requirements.txt
  tox.ini
Labels: enhancement

#7 Prevent from running more then one instance of any r/r modules
  hammer/library/utility.py
  hammer/reporting-remediation/remediation/clean_iam_key_rotation.py
  hammer/reporting-remediation/remediation/clean_iam_keys_inactive.py
  hammer/reporting-remediation/remediation/clean_public_ebs_snapshots.py
  hammer/reporting-remediation/remediation/clean_public_rds_snapshots.py
  hammer/reporting-remediation/remediation/clean_s3bucket_acl_permissions.py
  hammer/reporting-remediation/remediation/clean_s3bucket_policy_permissions.py
  hammer/reporting-remediation/remediation/clean_security_groups.py
  hammer/reporting-remediation/reporting/create_cloudtrail_tickets.py
  hammer/reporting-remediation/reporting/create_ebs_public_snapshot_issue_tickets.py
  hammer/reporting-remediation/reporting/create_ebs_volume_issue_tickets.py
  hammer/reporting-remediation/reporting/create_iam_key_inactive_tickets.py
  hammer/reporting-remediation/reporting/create_iam_key_rotation_tickets.py
  hammer/reporting-remediation/reporting/create_rds_public_snapshot_issue_tickets.py
  hammer/reporting-remediation/reporting/create_s3bucket_acl_issue_tickets.py
  hammer/reporting-remediation/reporting/create_s3bucket_policy_issue_tickets.py
  hammer/reporting-remediation/reporting/create_security_groups_tickets.py
Labels: bug
